### ISSUE TITLE
Sound category colors should be configurable

### ISSUE THREAD

**Issue by RhythmicSys** [haykam821/Colorful-Subtitles#2]
Love this resource but configurable color values would help immensely 😄

**Comment by haykam821** [comment]
Sound category colors can now be configured through `config/colorfulsubtitles.json`. The default configuration is:

```json
{
	"colors": {
		"music": "dark_purple",
		"record": "dark_red",
		"weather": "aqua",
		"block": "green",
		"hostile": "red",
		"neutral": "yellow",
		"player": "gold",
		"ambient": "gray",
		"voice": "light_purple"
	},
	"default_color": "white"
}
```

Colors can be specified as RGB format (`#768cfc`) or formatting colors (`dark_purple`).

**Comment by RhythmicSys** [comment]
awesome <3 thanks so much!
