### ISSUE TITLE
Update to 1.20?

### ISSUE THREAD

**Issue by Kavin7000** [haykam821/Colorful-Subtitles#6]

**Comment by davepusey** [comment]
I would also like a 1.20.1 update please.

**Comment by ccrowles** [comment]
Would also love an update to 1.20, it looks like a really useful mod.
(1.20 because they don't use 1.20.1 in the server I'm in)

**Comment by TheMrEngMan** [comment]
Fixed by #4

**Comment by haykam821** [comment]
[Version 1.3.0](https://github.com/haykam821/Colorful-Subtitles/releases/tag/1.3.0) supports Minecraft 1.20 and 1.20.1.
