### ISSUE TITLE
Could you add settings to change colors please?

### ISSUE THREAD

**Issue by TheCrossCarrier** [haykam821/Colorful-Subtitles#8]
Could you add settings to change colors please? <3

**Comment by haykam821** [comment]
Color configuration already exists, but you must edit a JSON file to change the configuration. The configuration path and schema is documented [here](https://github.com/haykam821/Colorful-Subtitles/issues/2#issuecomment-1369254328).

**Comment by TheCrossCarrier** [comment]
Thanks a lot sir! <3
Your mod is awesome!
